export const MOTION_PROMPTS: Record<string, string> = {
  walk: "A person walks naturally toward the camera for 3 steps with a relaxed human gait — heel-to-toe foot placement, subtle arm swing, slight body sway. After the third step, they smoothly stop and face the camera directly. Total duration: 6–7 seconds. Fabric responds dynamically to movement and settles naturally as the body stops. CRITICAL: The texture, color, stitching, and material detail of all clothing, footwear, and headwear must remain razor-sharp and identical to the reference photo throughout all motion — no blur or quality loss allowed. Camera is fixed. Cinematic lighting.",
  turn360: "The person performs one smooth, seamless 360-degree rotation in place over 7–8 seconds, pivoting on one foot at a perfectly consistent speed. Camera remains completely fixed. Every angle of the outfit is clearly visible. Fabric drapes and hangs naturally under gravity throughout the full rotation. CRITICAL: The texture, stitching, pattern, color, and material quality of all clothing, footwear, headwear, and eyewear must remain identical to the reference photo at every angle — no softening, darkening, or loss of detail at any point of the rotation. Studio lighting stays consistent from all angles.",
  pose: "The person transitions through exactly 2 distinct high-fashion editorial poses within 7–8 seconds. Each pose is held for 2–3 seconds with a slow, deliberate transition. Confident posture, elongated silhouette, intentional hand and arm placement. Subtle micro-movements keep the figure lifelike. CRITICAL: The fabric texture, color accuracy, material finish of all clothing, footwear, and headwear must preserve the exact same sharpness and detail as the user's reference photo in every pose — no blur, no color shift, no quality degradation allowed. No camera movement. Vogue editorial style lighting.",
  catwalk: "The person walks runway catwalk style toward the camera for 7–8 seconds — one foot placed precisely in front of the other, confident long stride, subtle rhythmic hip sway. Upright posture, shoulders back, chin slightly elevated. Clothing panels and fabric move naturally with each step. CRITICAL: The quality, texture, color, and sharp detail of all clothing, footwear, and headwear must remain fully consistent with the reference photo throughout the entire walk — no motion blur, no softening, no darkening of any worn item. Camera is fixed. High-end fashion runway lighting.",
  casual: "The person moves in a relaxed, natural manner for 7–8 seconds — gently shifting weight between feet, making small spontaneous hand gestures, slightly turning the torso left and right. Movements are unhurried and candid, like standing in a fitting room. Clothing shifts and settles naturally with each subtle motion. CRITICAL: The texture, color, material finish, and sharpness of all clothing, footwear, and headwear must exactly match the user's reference photo at all times — no blur, no quality loss, no color degradation during any movement. Camera is fixed.",
};

export const MOTION_LABELS: Record<string, { label: string; icon: string }> = {
  walk:    { label: "Walk",      icon: "🚶" },
  turn360: { label: "360° Spin", icon: "🔄" },
  pose:    { label: "Pose",      icon: "✨" },
  catwalk: { label: "Catwalk",   icon: "👑" },
  casual:  { label: "Casual",    icon: "😊" },
};
